# It is important to respect the naming convention for new Resources:
# https://innocap.atlassian.net/wiki/spaces/INNOCAP/pages/1703937/Naming+Convention

# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_wan
# terraform import azurerm_virtual_wan.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/virtualWans/testvwan


# Subnets specifications
# pres (appgw)
# dmz (permissions, access, filemage )
# web (ops, admin, )
# app (statengine, attribution)
# data (sql, redis)
# priv (private endpoint)
# int (ssis, ssrs, proxy blg, fss)

vwan:
  name: vWan-Prod-USe2-01
  subscription: 75641de5-1456-4853-bc77-dd7db76c35a1
  resource_group: Rg-vWan-Prod-01
  location: East US 2
  disable_vpn_encryption: false
  allow_branch_to_branch_traffic: true
  office365_local_breakout_category: None
  type: Standard
  tags:

# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub
# terraform import azurerm_virtual_hub.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/virtualHubs/hub1
hubs:
  - name: HubNet-Prod-UsE2-01
    subscription: 75641de5-1456-4853-bc77-dd7db76c35a1
    resource_group_name: Rg-vWan-Prod-01
    location: East US 2
    address_prefix: 10.50.0.0/23 #10.90.0.0/16
    sku: Standard
    virtual_wan_id:
    firewall:
      name:
      location:
      public_ip:
    tags:
    # DO NOT USE https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub_route_table
    # USE INSTEAD https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub_route_table_route
    route_tables:
      - name:
        virtual_hub_id:
        labels:
          - Default
        routes:
          - name:
            destinations_type:
            destinations: ["10.0.0.0/16"]
            next_hop_type: "ResourceId"
            next_hop: azurerm_virtual_hub_connection.example.id
    spokes:
      # automatically create connection between vnets and hub
      # https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub_connection
      - name:
        resource_group_name:
        address_space:
        location:
        bgp_community:
        ddos_protection_plan:
        dns_servers:
        edge_zone:
        flow_timeout_in_minutes:
        # https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet
        # terraform import azurerm_subnet.exampleSubnet /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Network/virtualNetworks/myvnet1/subnets/mysubnet1
        subnets:
          # each subnet creates its own NSG if enabled to be used after when applying rules. Defaults to true
          - name: snet-dev-app-usc-01
            address_prefixes: ["0.0.0.0/0"]
            service_endpoints:
            service_endpoint_policy_ids:
            private_endpoint_network_policies_enabled:
            create_nsg: false
            # for App Gateway
            delegation:
              name:

vnets:
# automatically create connection between vnets and hub
  # https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub_connection
  - name:
    resource_group_name:
    address_space:
    location:
    bgp_community:
    ddos_protection_plan:
    dns_servers:
    edge_zone:
    flow_timeout_in_minutes:
    # https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet
    # terraform import azurerm_subnet.exampleSubnet /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Network/virtualNetworks/myvnet1/subnets/mysubnet1
    subnets:
      # each subnet creates its own NSG if enabled to be used after when applying rules. Defaults to true
      - name: snet-dev-app-usc-01
        address_prefixes: ["0.0.0.0/0"]
        service_endpoints:
        service_endpoint_policy_ids:
        private_endpoint_network_policies_enabled:
        create_nsg: false
        # for App Gateway
        delegation:
          name: