location_code: cu
location: Central US

subscriptions:
  # Network
  - id: 75641de5-1456-4853-bc77-dd7db76c35a1
    function: network
    name: sb-net-prod-01
    legacy_name: Sb-NetHub-Prd-01

    hubs:
      - name: vhub-net-prod-uc-01
        legacy_name: HubNet-Prod-UsC-01
        subscription_id: 75641de5-1456-4853-bc77-dd7db76c35a1
        location: Central US
        address_prefix: 10.60.0.0/23
        sku: Standard
        tags:
          managed-by: terraform
          resource-name: vhub-net-prod-uc-01

        vpn:
          gateway_name: 01d29d7a32974121afadd8abdb92b84d-centralus-gw
          sites:
            - name: LegAzure-Prod-CAE-01
              location: canadaeast # ?? to validate
              address_cidrs: [ "10.32.0.0/16", "10.33.0.0/16" ]
              device_vendor: FortiGate
              routing:
                associated_route_table: /subscriptions/75641de5-1456-4853-bc77-dd7db76c35a1/resourceGroups/Rg-vWan-Prod-01/providers/Microsoft.Network/virtualHubs/HubNet-Prod-UsC-01/hubRouteTables/defaultRouteTable
                propagated_route_table:
                  labels: ["default"]
                  route_table_ids: ["/subscriptions/75641de5-1456-4853-bc77-dd7db76c35a1/resourceGroups/Rg-vWan-Prod-01/providers/Microsoft.Network/virtualHubs/HubNet-Prod-UsC-01/hubRouteTables/defaultRouteTable"]
              o365_policy:
                traffic_category:
                  allow_endpoint_enabled: false
                  default_endpoint_enabled: false
                  optimize_endpoint_enabled: false
              tags:
                managed-by: terraform
              links:
                - name: LegProdCAE01
                  fqdn: vpn.innocap.com
                  provider_name: Azure
                  speed_in_mbps: 100
                  bgp:
                    asn: 65309
                    peering_address: 169.254.17.133

        firewall:
          name: fw-net-prod-uc-01
          legacy_name: AzureFirewall_HubNet-Prod-UsC-01
          location: Central US
          sku_tier: Premium
          sku_name: AZFW_Hub
          tags:
            managed-by: terraform
            resource-name: fw-net-prod-uc-01

        firewall_policy:
          name: fwp-net-prod-uc-01
          legacy_name: FwPol-Prod-UsC-01
          location: Canada Central
          private_ip_ranges: ["255.255.255.255/32"]
          resource_group:
            name: rg-fwp-net-prod-uc-01
            legacy_name: Rg-FwPol-Prod-US-01
            location: East US 2 # should be -> Central US
            tags:
              managed-by: terraform
              resource-name: rg-fwp-net-prod-uc-01
          dns :
            proxy_enabled: false
            servers       : []
          intrusion_detection:
            mode : Alert
          threat_intelligence_allowlist :
            fqdns  : []
            ip_addresses  : []
          tags:
            managed-by: terraform
            resource-name: fwp-net-prod-uc-01

  # Platform
  - id: 4172118f-0fbf-4130-ba5b-5ad78292ae91
    name: sb-pfm-dev-01
    legacy_name: Sb-client-Dev-US-01

  - id: e4eb0487-0872-4b0f-9185-79cf4d6a2af1
    name: sb-pfm-qa-01
    legacy_name: Sb-Client-PProd-US-01
    spokes:

  - id: b69669b9-6d12-4ada-b44d-5f578b85f46c
    name: sb-pfm-prod-01
    legacy_name: Sb-Client-Prod-US-01

  # TO CREATE
  # - id:
  #   name: sb-pfm-dev-01
  #   legacy_name:


  # Corporate
  - id: d0c437f8-266d-4cd9-84cb-df09ee801e26
    name: sb-cpo-prod-01
    legacy_name: Sb-Corp-Prod-US

  - id: 9f6c36c6-042f-4bb1-9c8d-915a3f524c6e
    name: sb-cpo-prod-02
    legacy_name: Sb-Corp-Prod-IN

  #  Security
  # TO CREATE
  # - id:
  #   name: sb-sev-prod-01
  #   legacy_name:

  # IT Tools
  - id: 59d150e5-a66d-418f-8156-9b5b772a1922
    name:  sb-itt-prod-01
    legacy_name: Sb_ITTools-Prod-01

  # Identity
  - id: 99d9c0c8-690d-42ed-85c8-e910aae61413
    name: sb-id-prod-01
    legacy_name: Sb-Id-Prod-01

  # DevOps
  - id: 5a1019fa-917d-4ca0-8580-52ff2469e621
    name: sb-dvp-prod-01
    legacy_name: Sb-DevOps-Prod-01

  # IT Monitoring
  - id: 26a67cfa-69d2-48fc-a48a-d6aa5abe04ba
    name: sb-itm-prod-01
    legacy_name:   Sb-ITMon-Prod-01