vwan:
  name: vWan-Prod-USe2-01
  subscription: 75641de5-1456-4853-bc77-dd7db76c35a1
  resource_group: Rg-vWan-Prod-01
  location: East US 2
  disable_vpn_encryption: false
  allow_branch_to_branch_traffic: true
  office365_local_breakout_category: None
  type: Standard
  tags:
